[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx prisma generate", "npx prisma db push --accept-data-loss"]

[start]
cmd = "npx tsx src/server.ts"
