import { Reservation, User } from '../components/types';

const baseIso = (date: string) => new Date(date).toISOString();

export const MOCK_USERS: User[] = [
  {
    id: 'mock-student',
    email: 'lucie@vutbr.cz',
    firstName: 'Lucie',
    lastName: 'Riederová',
    role: 'STUDENT',
    isVerified: true,
    avatarIndex: 2,
  },
  {
    id: 'mock-ceo',
    email: 'sabina@vutbr.cz',
    firstName: 'Sabina',
    lastName: 'Hanzlíková',
    role: 'CEO',
    isVerified: false,
    avatarIndex: 5,
  },
  {
    id: 'mock-guide',
    email: 'guide@vutbr.cz',
    firstName: 'Marek',
    lastName: 'Bartoš',
    role: 'GUIDE',
    isVerified: true,
    avatarIndex: 1,
  },
  {
    id: 'mock-head-admin',
    email: 'admin@vutbr.cz',
    firstName: 'Eva',
    lastName: 'Černá',
    role: 'HEAD_ADMIN',
    isVerified: true,
    avatarIndex: 3,
  },
];

export const MOCK_RESERVATIONS: Reservation[] = [
  {
    id: 'res-student-1',
    roomName: 'Session Room',
    startTime: baseIso('2026-03-15T09:00:00Z'),
    endTime: baseIso('2026-03-15T11:00:00Z'),
    description: 'Sprint prep',
    type: 'SESSION',
    userId: 'mock-student',
    userName: 'Lucie Riederová',
    priorityLevel: 1,
    status: 'active',
  },
  {
    id: 'res-student-2',
    roomName: 'Meeting Room',
    startTime: baseIso('2026-03-18T13:30:00Z'),
    endTime: baseIso('2026-03-18T15:30:00Z'),
    description: 'Design critique',
    type: 'MEETING',
    userId: 'mock-student',
    userName: 'Lucie Riederová',
    priorityLevel: 1,
    status: 'active',
  },
  {
    id: 'res-ceo-1',
    roomName: 'The Stage',
    startTime: baseIso('2026-03-17T11:00:00Z'),
    endTime: baseIso('2026-03-17T13:00:00Z'),
    description: 'Investor prep',
    type: 'PITCHDECK',
    userId: 'mock-ceo',
    userName: 'Sabina H.',
    priorityLevel: 2,
    status: 'active',
  },
  {
    id: 'res-guide-1',
    roomName: 'Panda Room',
    startTime: baseIso('2026-03-16T10:00:00Z'),
    endTime: baseIso('2026-03-16T12:00:00Z'),
    description: 'Mentor session',
    type: 'SESSION',
    userId: 'mock-guide',
    userName: 'Marek B.',
    priorityLevel: 3,
    status: 'active',
  },
  {
    id: 'res-cancelled-1',
    roomName: 'Panda Room',
    startTime: baseIso('2026-03-12T15:00:00Z'),
    endTime: baseIso('2026-03-12T17:30:00Z'),
    description: 'Cancelled prep',
    type: 'MEETING',
    userId: 'mock-student',
    userName: 'Lucie Riederová',
    priorityLevel: 1,
    status: 'cancelled',
  },
];
